import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-chat-events',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './chat-events.component.html',
  styleUrl: './chat-events.component.css'
})
export class ChatEventsComponent {

  chatEvents = [
    {
      name: 'Follows',
      description: {
        EN: 'Every time a user follows the streamer, a message will be sent to the chat.',
        ES: 'Cada vez que un usuario sigue al streamer, se enviará un mensaje al chat.'
      },
      icon: 'user-plus',
      color: 'bg-purple-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Follows are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Follows are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Follows are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Subscriptions',
      description: {
        EN: 'Celebrate when viewers subscribe to your channel.',
        ES: 'Celebra cuando los espectadores se suscriban a tu canal.'
      },
      icon: 'heart',
      color: 'bg-red-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Subscriptions are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Subscriptions are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Subscriptions are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: false
    },
    {
      name: 'Donations',
      description: {
        EN: 'Show appreciation for viewer donations with custom messages.',
        ES: 'Muestra agradecimiento por las donaciones de los espectadores con mensajes personalizados.'
      },
      icon: 'gift',
      color: 'bg-green-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Donations are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Donations are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Donations are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: true
    },
    {
      name: 'Bits',
      description: {
        EN: 'Celebrate when viewers cheer with bits.',
        ES: 'Celebra cuando los espectadores animen con bits.'
      },
      icon: 'zap',
      color: 'bg-yellow-500',
      textColor: 'text-black',
      enabled: true,
      enabled_message: 'Bits are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Bits are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Bits are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Raids',
      description: {
        EN: 'Welcome raiders when they join your stream.',
        ES: 'Da la bienvenida a los raiders cuando se unan a tu stream.'
      },
      icon: 'users',
      color: 'bg-blue-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Raids are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Raids are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Raids are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Hosts',
      description: {
        EN: 'Thank viewers when they host your channel.',
        ES: 'Agradece a los espectadores cuando hagan host de tu canal.'
      },
      icon: 'tv',
      color: 'bg-indigo-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Hosts are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Hosts are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Hosts are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'First Time Chatters',
      description: {
        EN: 'Welcome new chatters to your community.',
        ES: 'Da la bienvenida a nuevos chatters a tu comunidad.'
      },
      icon: 'message-circle',
      color: 'bg-pink-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'First time chatters are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'First time chatters are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'First time chatters are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Stream Milestones',
      description: {
        EN: 'Celebrate reaching viewer count milestones.',
        ES: 'Celebra alcanzar hitos de espectadores.'
      },
      icon: 'trophy',
      color: 'bg-amber-500',
      textColor: 'text-black',
      enabled: true,
      enabled_message: 'Stream milestones are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Stream milestones are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Stream milestones are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: false
    },
    {
      name: 'Chat Commands',
      description: {
        EN: 'Custom commands that viewers can use in chat.',
        ES: 'Comandos personalizados que los espectadores pueden usar en el chat.'
      },
      icon: 'terminal',
      color: 'bg-gray-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Chat commands are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Chat commands are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: true,
      maintenance_message: 'Chat commands are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: true
    },
    {
      name: 'Poll Results',
      description: {
        EN: 'Announce the results of chat polls.',
        ES: 'Anuncia los resultados de las encuestas del chat.'
      },
      icon: 'bar-chart-3',
      color: 'bg-teal-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Poll results are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Poll results are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Poll results are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Channel Points',
      description: {
        EN: 'Reward viewers for redeeming channel points.',
        ES: 'Recompensa a los espectadores por canjear puntos del canal.'
      },
      icon: 'star',
      color: 'bg-orange-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Channel points are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Channel points are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Channel points are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Emote Only Mode',
      description: {
        EN: 'Notify when emote-only mode is toggled.',
        ES: 'Notifica cuando se active el modo solo emotes.'
      },
      icon: 'smile',
      color: 'bg-cyan-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Emote only mode is enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Emote only mode is disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Emote only mode is in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Slow Mode',
      description: {
        EN: 'Alert when slow mode is activated in chat.',
        ES: 'Alerta cuando se active el modo lento en el chat.'
      },
      icon: 'clock',
      color: 'bg-slate-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Slow mode alerts are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Slow mode alerts are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Slow mode alerts are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Subscriber Milestones',
      description: {
        EN: 'Celebrate reaching subscriber count milestones.',
        ES: 'Celebra alcanzar hitos de suscriptores.'
      },
      icon: 'award',
      color: 'bg-rose-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Subscriber milestones are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Subscriber milestones are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Subscriber milestones are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: true
    },
    {
      name: 'Chat Timeouts',
      description: {
        EN: 'Notify when users are timed out in chat.',
        ES: 'Notifica cuando los usuarios sean silenciados en el chat.'
      },
      icon: 'mute',
      color: 'bg-red-600',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Chat timeouts are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Chat timeouts are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Chat timeouts are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Stream Schedule',
      description: {
        EN: 'Remind viewers about upcoming streams.',
        ES: 'Recuerda a los espectadores sobre próximos streams.'
      },
      icon: 'calendar',
      color: 'bg-emerald-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Stream schedule reminders are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Stream schedule reminders are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Stream schedule reminders are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: false
    },
    {
      name: 'Social Media Links',
      description: {
        EN: 'Share social media links periodically.',
        ES: 'Comparte enlaces de redes sociales periódicamente.'
      },
      icon: 'share-2',
      color: 'bg-violet-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Social media links are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Social media links are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Social media links are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Game Alerts',
      description: {
        EN: 'Notify when switching games or starting new ones.',
        ES: 'Notifica cuando cambies de juego o inicies nuevos.'
      },
      icon: 'gamepad-2',
      color: 'bg-lime-500',
      textColor: 'text-black',
      enabled: true,
      enabled_message: 'Game alerts are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Game alerts are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Game alerts are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: false,
      premium_plus: false
    },
    {
      name: 'Music Requests',
      description: {
        EN: 'Handle music requests from chat viewers.',
        ES: 'Maneja solicitudes de música de los espectadores del chat.'
      },
      icon: 'music',
      color: 'bg-fuchsia-500',
      textColor: 'text-white',
      enabled: false,
      enabled_message: 'Music requests are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: true,
      disabled_message: 'Music requests are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: true,
      maintenance_message: 'Music requests are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: true
    },
    {
      name: 'Clip Highlights',
      description: {
        EN: 'Automatically share and celebrate new clips.',
        ES: 'Comparte y celebra automáticamente nuevos clips.'
      },
      icon: 'video',
      color: 'bg-sky-500',
      textColor: 'text-white',
      enabled: true,
      enabled_message: 'Clip highlights are enabled',
      enabled_message_color: 'text-green-500',
      enabled_message_icon: 'check',
      disabled: false,
      disabled_message: 'Clip highlights are disabled',
      disabled_message_color: 'text-red-500',
      disabled_message_icon: 'x',
      maintenance: false,
      maintenance_message: 'Clip highlights are in maintenance',
      maintenance_message_color: 'text-yellow-500',
      maintenance_message_icon: 'wrench',
      premium: true,
      premium_plus: true
    }
  ]
  
}
